### ISSUE TITLE
Exscansion Bugs with RESSCAN Setting

### ISSUE THREAD

**Issue by BabyGrootTheEpic** [ReikaKalseki/Reika_SubnauticaModsShared#10]
With the RESSCAN setting on, the scanner room can't scan for diamond or lithium (neither of which can be scanned with the scanner). The scanner room is also able to scan for Crystalline sulfur, Magnetite, and Shale chunks before they've been scanned with the scanner.

**Comment by ReikaKalseki** [comment]
Fixed.
