### ISSUE TITLE
the glassforest wreck doesnt apear to be spawning even after the sunbeam has been destroyed

### ISSUE THREAD

**Issue by quindao** [ReikaKalseki/Reika_SubnauticaModsShared#12]
image at coorodinates listed in the xml
![image](https://github.com/ReikaKalseki/Reika_SubnauticaModsShared/assets/39583189/0dfc0c9e-405c-48e1-bccd-2a1aea174e5a)

**Comment by quindao** [comment]
my save was created in version 24 of SeaToSea if that matters but i have been keeping it updated

**Comment by quindao** [comment]
and just in case its a known mod conflict here's my mod list 
![image](https://github.com/ReikaKalseki/Reika_SubnauticaModsShared/assets/39583189/69f52417-0557-4739-be08-be50f19ebfc6)

**Comment by quindao** [comment]
heres the qmod log https://drive.google.com/file/d/1Wurct9u1otL3CGlUEO86-F70Vu6N34wC/view?usp=sharing

**Comment by quindao** [comment]
i did some testing in a fresh save and forced the sunbeam event to play and still no wreck I did however find an error related to the wreck 
NullReferenceException: Object reference not set to an instance of an object
  at ReikaKalseki.SeaToSea.GlassForestWreck.Update () [0x00065] in <1d5d2b043f614758ad3b926b4228b0b0>:0

**Comment by ReikaKalseki** [comment]
Those things are entirely unrelated. Also, the wreck is throwing no errors for me.
