### ISSUE TITLE
"The following mods could not be loaded: SeaToSea"

### ISSUE THREAD

**Issue by Sapphydanimbat** [ReikaKalseki/Reika_SubnauticaModsShared#15]
So I've been trying to play with SeaToSea on, but every time I launch the game it gives me an error saying the mod could not be loaded. When I check the log, the best I can figure out is that for some reason it might not like being preloaded, but I'll be honest, I could also be wrong, which is why I included the log file.
[qmodmanager_log-Subnautica.txt](https://github.com/ReikaKalseki/Reika_SubnauticaModsShared/files/12244350/qmodmanager_log-Subnautica.txt)

**Comment by ReikaKalseki** [comment]
You are missing dependencies.
