### ISSUE TITLE
Re(ef)balance, Aqueous Engineering and Exscansion not loading into the game

### ISSUE THREAD

**Issue by RiccaWasHere** [ReikaKalseki/Reika_SubnauticaModsShared#19]
So i istalled all the 7 mods required for Sea to Sea but when i open the game it tells me that it couldn't load the 3 mods i put into the title. I went to the log and it tells me that DIAlterra is required but that mod  (i presume) is Dragon industries Alterra division and i have this mod installed but it doesn't work either.

**Comment by ReikaKalseki** [comment]
Then you are missing something else. It says exactly what you need to have (and in some cases not have).
