### ISSUE TITLE
Pink blast destroys bases in SeatoSea

### ISSUE THREAD

**Issue by missingtexturesgit** [ReikaKalseki/Reika_SubnauticaModsShared#2]
I noticed when base building with seatosea installed there will occasionally be a large pink blast that causes a lot of leaks,it's frustrating and really strange,I noticed it in a void spikes base but I've heard someone else say it occured in the safe shallows

**Comment by xilni** [comment]
Red smoke effect causing the same damage across my Safe Shallows base. even damaging lockers.

**Comment by ReikaKalseki** [comment]
...It is *damaging* the base?

**Comment by xilni** [comment]
It creates leaks everywhere and the leaks flood the base.

**Comment by ReikaKalseki** [comment]
This was in fact Ecocean's exploding anchor pods.
