### ISSUE TITLE
Ecocean ERROR Loading Mod

### ISSUE THREAD

**Issue by BYRedex** [ReikaKalseki/Reika_SubnauticaModsShared#3]
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
[SMLHelper/Warn] CustomWorldEntityInfo already exists for 'LAVASHROOM'.
Original value has been overwritten by later entry.
So far we have discarded or overwritten 1 entries for 'LAVASHROOM'.
[QModManager:ERROR] Invoking the specified entry method "Load" failed for mod "ReikaKalseki.Ecocean"

[QModManager:ERROR] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: void SMLHelper.V2.Handlers.SpawnInfo..ctor(string,UnityEngine.Vector3,UnityEngine.Quaternion,System.Action`1<UnityEngine.GameObject>)

**Comment by ReikaKalseki** [comment]
This is caused by an outdated version of SML.
