### ISSUE TITLE
Lifepod 9 not showing

### ISSUE THREAD

**Issue by Darklaser38** [ReikaKalseki/Reika_SubnauticaModsShared#5]
The lifepod 9 is not showing the signal is here but not the lifepod.
I created a new world for playing with the c2c mod.
I have no error of the mod and its working very well except for this
![2023-03-06_00001](https://user-images.githubusercontent.com/127137441/223191949-c9e9ab70-ae8b-47cf-9ae4-099f6cd8766b.jpg)

**Comment by ReikaKalseki** [comment]
Are you using a system language with a number formatting different than English? There is currently a known issue where if you are using languages that format numbers differently - eg `174,19` instead of `174.19` or `293-8E` instead of `-293.8` the worldgen fails to load. 

See #4.

**Comment by Darklaser38** [comment]
Hello thanks for the quick answer
So i check the number formatting and changing it of french to english and it worked !
Thanks you for you help and from now im going to use the english format instead of the baguette format. (yeah i'm french)

**Comment by ReikaKalseki** [comment]
This is fixed.
