### ISSUE TITLE
Enzyme recipes progression bug

### ISSUE THREAD

**Issue by BSP0p** [ReikaKalseki/Reika_SubnauticaModsShared#6]
Enzyme recipes work in a loop and cannot be crafted. To make a lysing enzyme, you need bacteria samples, which requires digestive enzymes made from the lysing enzyme. ~~I have searched the source code and world gen files and have not found any other way of obtaining these items.~~

![1](https://user-images.githubusercontent.com/78181661/223765622-d4fc9b7e-3b70-4dab-abbf-efa3c2026647.png)
![2](https://user-images.githubusercontent.com/78181661/223765642-b3e48239-cad3-4cb0-9709-a64212469469.png)
![3](https://user-images.githubusercontent.com/78181661/223765650-c8242659-5f1f-403b-887a-d3bbfbbeef11.png)

Edit:
It seems that the recipe is being overwritten. This probably happens with a few other items crafted in the bioprocessor.

```(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)
[SMLHelper/Warn] CustomTechData already exists for 'TreaderEnzymes_delegate'.
Original value has been overwritten by later entry.
So far we have discarded or overwritten 1 entries for 'TreaderEnzymes_delegate'.
[SMLHelper/Warn] CustomTechData already exists for 'TreaderEnzymes_delegate'.
Original value has been overwritten by later entry.
So far we have discarded or overwritten 2 entries for 'TreaderEnzymes_delegate'.
SEATOSEA: Adding SeaTreaderPoopx1 to recipe 11129```

Edit 2:
This appears to have been fixed in the latest update. Sorry for the inconvenience.

**Comment by ReikaKalseki** [comment]
The recipe was always usable, just not listed.
