### ISSUE TITLE
Ecocean Seamoth Sonar attracts creatures

### ISSUE THREAD

**Issue by BabyGrootTheEpic** [ReikaKalseki/Reika_SubnauticaModsShared#8]
With Ecoceon installed, using the Seamoth's Sonar attracts mosts creatures to the Seamoth. This seems to be the same effect as what the mod adds to the Cyclops' horn.

I'm usually spamming my sonar wherever I go, so within a few hours of getting my seamoth in a Sea To Sea save I noticed a bunch of issues. Reefbacks are everywhere I go (even the jellyshroom caves), usually moving abnormally fast and/or clipping into the ground. Ampeels will follow me very far outside their biomes. Bonesharks will attack me in abnormally large groups whenever I approach their biomes. Just before I stopped playing to troubleshoot I had a reaper, 2 ampeels, an adult reefback, and at least 6 shoals of fish follow me from mountains all the way to the shallows just trying to escape the reaper.

Any chance you could fix this, or if this is intentional add a config option to disable it?

**Comment by ReikaKalseki** [comment]
This is already fixed.
