### ISSUE TITLE
Duplicated Leviathans and Respawning Base Pieces

### ISSUE THREAD

**Issue by BabyGrootTheEpic** [ReikaKalseki/Reika_SubnauticaModsShared#9]
The Leviathans spawned by these mods are being spawned every time a save is loaded, not just when the save is created. To test I made a new creative save, teleported to the southern spot in dunes where one of your mods spawns a Reaper (warp -1133 -260 -260) and saved. After restarting my game, there were 2 reapers instead of just 1.

Deconstructed base pieces from the seabase wrecks added by C2C will respawn when the game is restarted, allowing for infinite farming of their resources.

I was able to recreate both of these consistently with just C2C and its dependecies.

**Comment by BabyGrootTheEpic** [comment]
At least for me, the duplicating leviathans seems to be fixed. I found a few more bugs relating to the respawning base pieces though.

When I initially load a save, some pieces of the blood kelp seabase wreck are missing, and all the hatches there can be used. Except during said initial load, the bioprocessor there seems to spawn every time the base is loaded, even if the previous one wasn't deconstructed. The most recently spawned one won't have its full model, only the monitor part of it. Some of them will also drain power from a player made seabase, seeming to happen more often if either the player or a beacon is currently near them. In my survival save the large quantity of them is draining power from my main base faster than it makes power.

The following steps consistently recreate all of these with just C2C and its dependencies:
1. Make a non-creative world
2. Use the commands `invisible` and `oxygen`
3. Use the command `c2cpoi bkelpbase` and see that some parts are missing
4. Test that the exterior hatches are useable
5. Go somewhere safe (the invisible and oxygen commands don't persist through reloading a save)
6. Save and reload the save file (according to a smlhelper dev it doesn't bug out from just re-entering the save without fully restarting anymore, but I still do just in case)
7. Use the commands `invisible`, `oxygen`, `item builder`, and `nocost`
8. Make a base powered by a solar panel anywhere and remember its coordinates to teleport back to later
9. Wait for the solar panel to make some power (how much doesn't matter)
10. Use the `night` command to stop the solar panel from making power and remember how much it has
11. Use the command `warp -1337 -660 -430` to teleport to the bioprocessor
12. Teleport far away enough for the base to unload
13. Teleport back to the bioprocessor
14. Confirm that there are two bioprocessors by deconstructing one and/or messing with their inventories
15. Teleport to the base you built and see that there is less power than when you left it

If the solar panel isn't actively losing power:

16. Teleport to and from the bioprocessor a few times
17. Teleport to your base
18. If the solar panel is out of power, use the `day` command for the solar panel to generate more
19. Use the `night` command if necessary and see the solar panel start losing power

**Comment by ReikaKalseki** [comment]
These have all been fixed.
